### ISSUE TITLE
Add images of technologies in the stack instead of text list

### ISSUE THREAD

**Issue by raulcd** [te-chie-la/techiela-web#13]

**Comment by franhp** [comment]
The new background color of this section does not match the current palette, I'll be looking into that

**Comment by franhp** [comment]
Guise ... please choose:

http://postimg.org/gallery/lu1h3y8s/

**Comment by raulcd** [comment]
I am not a designer so for me all look the same. What about maintaining the old color but adding the images in a white circle? Similar to the 'about' 'blog' logos but with white background in the circle.
Does it make sense?

Otherwise choose the color you prefer.

BYW you can add Tux if you want.
